# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run

environment:
   SERVER_IP_ADDRESS: 192.168.12.185
   DOKKU_APP: circlecidemo
   TRAVIS: "false"
steps:
# Use BASH instead of DASH! see: https://ubuntuforums.org/showthread.php?t=1932504
      - run: ls -al /bin/sh && sudo rm /bin/sh && sudo ln -s /bin/bash /bin/sh && ls -al /bin/sh
      # test shell script:
      - run: echo ${SERVER_IP_ADDRESS}
      - run: echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run: sh bin/deploy.sh
